# Find free ports for DB and backend if defaults are in use and write .env
$defaults = @{DB_HOST_PORT=5432; BACKEND_HOST_PORT=8080; BACKEND_ACTUATOR_HOST_PORT=8081}
$result = @{}
foreach ($k in $defaults.Keys) {
  $port = $defaults[$k]
  while (netstat -ano | Select-String ":$port\s" ) {
    $port++
  }
  $result[$k] = $port
}
$envLines = $result.GetEnumerator() | ForEach-Object { "{0}={1}" -f $_.Key,$_.Value }
$envContent = $envLines -join "`n"
Set-Content -Path (Join-Path $PSScriptRoot "..\.env") -Value "# Generated by select-free-ports.ps1`n$envContent"
Write-Output "Wrote .env with:`n$envContent"